version: "3.3"

services:
    web:
        build: .
        command: "python3 /byro/src/manage.py runserver 0.0.0.0:8020"
        environment:
            PYTHONUNBUFFERED: 0
            DJANGO_SETTINGS_MODULE: byro.settings
            DEVELOPMENT: 1
            BYRO_CONFIG_FILE: /byro/src/byro.docker.cfg
        depends_on:
            - db
        volumes:
            - ..:/byro
        ports:
            - "8020:8020"
    db:
        container_name: db
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: byro
            POSTGRES_DB: byro
            POSTGRES_USER: byro
        volumes:
            - data:/var/lib/postgresql/data
volumes:
    data:
